<?php
namespace UCBRecommendDefines;

if ( !defined( 'UCB_RECOMMEND_PLUGIN' ) )
	exit;

if ( !defined( 'UCB_RECOMMEND_TABLE_VERSION' ) ) {
	define( 'UCB_RECOMMEND_TABLE_VERSION', '0.0.0.0.1' );
}

//lib dir
define( 'UCB_RECOMMEND_LIB_API_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "apis" );
define( 'UCB_RECOMMEND_LIB_MODELS_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "models" );
define( 'UCB_RECOMMEND_LIB_VIEWS_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "views" );
define( 'UCB_RECOMMEND_LIB_MAIL_TEMPLATE_DIR', UCB_RECOMMEND_LIB_VIEWS_DIR . DIRECTORY_SEPARATOR . "mail_template" );
define( 'UCB_RECOMMEND_LIB_SERVICES_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "services" );
define( 'UCB_RECOMMEND_LIB_TEST_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "test" );
define( 'UCB_RECOMMEND_LIB_ASSETS_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "public" );
define( 'UCB_RECOMMEND_LIB_CSS_DIR', UCB_RECOMMEND_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "css" );
define( 'UCB_RECOMMEND_LIB_JS_DIR', UCB_RECOMMEND_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "js" );
define( 'UCB_RECOMMEND_LIB_IMG_DIR', UCB_RECOMMEND_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "img" );
define( 'UCB_RECOMMEND_LIB_FONT_DIR', UCB_RECOMMEND_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "fonts" );
define( 'UCB_RECOMMEND_LIB_PLUGINS_DIR', UCB_RECOMMEND_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "plugins" );
define( 'UCB_RECOMMEND_LIB_LIBRARY_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "library" );
define( 'UCB_RECOMMEND_LIB_CONFIGS_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "configs" );
define( 'UCB_RECOMMEND_LIB_DIRECT_API_DIR', UCB_RECOMMEND_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "direct-api" );

//dir
define( 'UCB_RECOMMEND_CONTROLLERS_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "controllers" );
define( 'UCB_RECOMMEND_API_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "apis" );
define( 'UCB_RECOMMEND_MODELS_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "models" );
define( 'UCB_RECOMMEND_VIEWS_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "views" );
define( 'UCB_RECOMMEND_MAIL_TEMPLATE_DIR', UCB_RECOMMEND_VIEWS_DIR . DIRECTORY_SEPARATOR . "mail_template" );
define( 'UCB_RECOMMEND_SERVICES_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "services" );
define( 'UCB_RECOMMEND_TEST_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "test" );
define( 'UCB_RECOMMEND_ASSETS_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "public" );
define( 'UCB_RECOMMEND_CSS_DIR', UCB_RECOMMEND_ASSETS_DIR . DIRECTORY_SEPARATOR . "css" );
define( 'UCB_RECOMMEND_JS_DIR', UCB_RECOMMEND_ASSETS_DIR . DIRECTORY_SEPARATOR . "js" );
define( 'UCB_RECOMMEND_IMG_DIR', UCB_RECOMMEND_ASSETS_DIR . DIRECTORY_SEPARATOR . "img" );
define( 'UCB_RECOMMEND_FONT_DIR', UCB_RECOMMEND_ASSETS_DIR . DIRECTORY_SEPARATOR . "fonts" );
define( 'UCB_RECOMMEND_PLUGINS_DIR', UCB_RECOMMEND_ASSETS_DIR . DIRECTORY_SEPARATOR . "plugins" );
define( 'UCB_RECOMMEND_LOG_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "logs" );
define( 'UCB_RECOMMEND_TMP_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "tmp" );
define( 'UCB_RECOMMEND_UPLOAD_DIR', UCB_RECOMMEND_ROOT_DIR . DIRECTORY_SEPARATOR . "upload" );

//lib url
define( 'UCB_RECOMMEND_LIB_PLUGIN_URL', plugins_url( '', UCB_RECOMMEND_LIB_COMMON_DIR ) );
define( 'UCB_RECOMMEND_LIB_ASSETS_URL', UCB_RECOMMEND_LIB_PLUGIN_URL . "/public" );
define( 'UCB_RECOMMEND_LIB_CSS_URL', UCB_RECOMMEND_LIB_ASSETS_URL . "/css" );
define( 'UCB_RECOMMEND_LIB_JS_URL', UCB_RECOMMEND_LIB_ASSETS_URL . "/js" );
define( 'UCB_RECOMMEND_LIB_IMG_URL', UCB_RECOMMEND_LIB_ASSETS_URL . "/img" );
define( 'UCB_RECOMMEND_LIB_FONT_URL', UCB_RECOMMEND_LIB_ASSETS_URL . "/fonts" );
define( 'UCB_RECOMMEND_LIB_PLUGINS_URL', UCB_RECOMMEND_LIB_ASSETS_URL . "/plugins" );
define( 'UCB_RECOMMEND_LIB_DIRECT_API_URL', UCB_RECOMMEND_LIB_PLUGIN_URL . "/direct-api" );

//url
define( 'UCB_RECOMMEND_PLUGIN_URL', plugins_url( '', UCB_RECOMMEND_COMMON_DIR ) );
define( 'UCB_RECOMMEND_ASSETS_URL', UCB_RECOMMEND_PLUGIN_URL . "/public" );
define( 'UCB_RECOMMEND_CSS_URL', UCB_RECOMMEND_ASSETS_URL . "/css" );
define( 'UCB_RECOMMEND_JS_URL', UCB_RECOMMEND_ASSETS_URL . "/js" );
define( 'UCB_RECOMMEND_IMG_URL', UCB_RECOMMEND_ASSETS_URL . "/img" );
define( 'UCB_RECOMMEND_FONT_URL', UCB_RECOMMEND_ASSETS_URL . "/fonts" );
define( 'UCB_RECOMMEND_PLUGINS_URL', UCB_RECOMMEND_ASSETS_URL . "/plugins" );
define( 'UCB_RECOMMEND_UPLOAD_URL', UCB_RECOMMEND_PLUGIN_URL . "/upload" );

//log file
define( 'UCB_RECOMMEND_LOG_FILE', UCB_RECOMMEND_LOG_DIR . DIRECTORY_SEPARATOR . "ucbr.log" );

//update info
define( 'UCB_RECOMMEND_UPDATE_INFO_FILE_URL', "https://raw.githubusercontent.com/123teru321/UCB-Recommend/master/update.json" );
